services:
  api:
    env_file:
      - .env.prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__PG=Server=postgres;Port=5432;Database=TestDb;User Id=TestUser;Password=1234;SearchPath=public;Pooling=false;Timeout=300;CommandTimeout=300;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/.aspnet/https/aspnetapp.pfx
      - Serilog__WriteTo__2__Args__serverUrl=http://seq:80
    ports:
      - "5120:8080"
      - "7054:8081"
    restart: unless-stopped
    depends_on:
      - postgres
      - seq

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=TestDb
      - POSTGRES_USER=TestUser
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  seq_data: